### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by showdy** [SmartToolFactory/Jetpack-Compose-Tutorials#22]
java.lang.IllegalStateException: The offset was read before being initialized. Did you access the offset in a phase before layout, like effects or composition?
                                                                                                    	at androidx.compose.material.AnchoredDraggableState.requireOffset(AnchoredDraggable.kt:214)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2$3.invoke-Bjo55l4(ModalBottomSheet.kt:622)
                                                                                                    	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$2$3.invoke(ModalBottomSheet.kt:618)
                                                                                                    	at androidx.compose.foundation.layout.OffsetPxNode$measure$1.invoke(Offset.kt:247)
                                                                                                    	at androidx.compose.foundation.layout.OffsetPxNode$measure$1.invoke(Offset.kt:246)
                                                                                                    	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                                                                                    	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:178)
                                                                                                    	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:156)
                                                                                                    	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:452)
                                                                                                    	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:204)
                                                                                                    	at androidx.compose.foundation.layout.FillNode$measure$1.invoke(Size.kt:704)
                                                                                                    	at androidx.compose.foundation.layout.FillNode$measure$1.invoke(Size.kt:703)

**Comment by shahzadansari** [comment]
Fixed in #44
