### ISSUE TITLE
Tutorial 2.4 Preview Broken

### ISSUE THREAD

**Issue by shahzadansari** [SmartToolFactory/Jetpack-Compose-Tutorials#26]
Preview is broken for **Tutorial 2.4** with following crash logs in **Design** tab.
```
java.lang.RuntimeException: Unable to find metadata to parse GlideModules 
at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:56)
at com.bumptech.glide.Glide.initializeGlide(Glide.java:254)
at com.bumptech.glide.Glide.initializeGlide(Glide.java:242)
at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:201)
at com.bumptech.glide.Glide.get(Glide.java:182)
at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
at com.bumptech.glide.Glide.with(Glide.java:776)
at com.smarttoolfactory.tutorial1_1basics.chapter2_material_widgets.Tutorial2_4ImageKt.ImageDownloadWithGlideExample(Tutorial2_4Image.kt:554)
at com.smarttoolfactory.tutorial1_1basics.chapter2_material_widgets.ComposableSingletons$Tutorial2_4ImageKt$lambda-1$1.invoke(Tutorial2_4Image.kt:131)
```

**Comment by shahzadansari** [comment]
Fixed in #27
